set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clrn]
set_property PACKAGE_PIN J15 [get_ports clrn]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN L16 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports game_start_end]
set_property PACKAGE_PIN N17 [get_ports game_start_end]
set_property IOSTANDARD LVCMOS33 [get_ports turn_up]
set_property PACKAGE_PIN M18 [get_ports turn_up]
set_property IOSTANDARD LVCMOS33 [get_ports turn_down]
set_property PACKAGE_PIN P18 [get_ports turn_down]
set_property IOSTANDARD LVCMOS33 [get_ports turn_left]
set_property PACKAGE_PIN P17 [get_ports turn_left]
set_property IOSTANDARD LVCMOS33 [get_ports turn_right]
set_property PACKAGE_PIN M17 [get_ports turn_right]


set_property IOSTANDARD LVCMOS33 [get_ports sia]
set_property PACKAGE_PIN C17 [get_ports sia]
set_property IOSTANDARD LVCMOS33 [get_ports sib]
set_property PACKAGE_PIN D18 [get_ports sib]
set_property IOSTANDARD LVCMOS33 [get_ports sw]
set_property PACKAGE_PIN E18 [get_ports sw]


set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property PACKAGE_PIN B11 [get_ports hs]
set_property IOSTANDARD LVCMOS33 [get_ports vs]
set_property PACKAGE_PIN B12 [get_ports vs]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN A3 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN B4 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN C5 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN A4 [get_ports {vga_r[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN C6 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN A5 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN B6 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN A6 [get_ports {vga_g[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN B7 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN C7 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN D7 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN D8 [get_ports {vga_b[3]}]


set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sib_IBUF] 
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rst_IBUF] 
